#!/bin/bash

#Start Bluetooth
[[ ! -f ~/.bluetooth_devices ]] && notify-send "No saved bluetooth connection. ~/.bluetooth_devices not found" && exit

devices=$(cat ~/.bluetooth_devices)
device=$( echo "$devices" | dmenu -b )
deviceName=$(echo "$device" | awk '{print $1}' | tr '_' ' ')
deviceIP=$(echo "$device" | awk '{print $2}')
[[ -z $deviceName ]] && exit

#Connect to device
# sudo systemctl stop bluetooth
sudo systemctl restart bluetooth
sleep 1
echo $deviceIP
bluetoothctl -- connect "$deviceIP"
rc=$?
[[ $rc -eq 0 ]] && notify-send "Connected to $deviceName"
[[ $rc -ne 0 ]] && notify-send "Failed to connect to $deviceName" && exit

#Switch audio output, loop since device
sinkID=''
count=99
while [ -z $sinkID ] && [ $count -ne 0 ]
do
  sinkID=$(echo $deviceIP | sed "s/:/_/g" | xargs -I {} sh -c "pacmd list-sinks | grep -iPo '(?<=card: )(\d+)(?= <bluez_card\.{}>)'")
  ((count--))
  echo "count is $count"
  sleep 1
done
echo "sinkID is $sinkID"
[[ -z $sinkID ]] && notify-send "Sink switching timed out. Please do that manually" && exit
pacmd list-sink-inputs | grep -iPo "(?<=index: )(\d+)" | xargs -I {} pacmd move-sink-input {} "$sinkID"

