#!/bin/bash

latestWallpaper=$(cat /tmp/wallpaper_cycle | tail -1)

[[ $latestWallpaper == "" ]] && exit 1

rm -rf $latestWallpaper

# notify-send "Delete $latestWallpaper"

# Empty log file so no more confusion boi
: > /tmp/wallpaper_cycle

# Get a new wallpaper in place
sh $HOME/scripts/randomWallpaper
