#!/usr/bin/env sh

# The famous "get a menu of emojis to copy" script.

# Must have xclip installed to even show menu.
pacman -Qi xclip >/dev/null || exit

chosen=$(grep -v "#" $HOME/scripts/emoji | dmenu -b -i -l 20 -fn Iosevka-10)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &

# s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
# echo "$s" | tr -d '\n' | xclip
# notify-send "'$s' copied to primary." &
