#!/bin/bash

# date +"%m/%d/%Y" | xclip -selection clipboard && xdotool key ctrl+v

instantDate() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"
    echo $var
    echo $var | xclip -selection clipboard
    xdotool key ctrl+v
}

instantDate $(date +"%m/%d/%Y")
