#!/bin/bash

layoutpath=$HOME/.screenlayout/
layout="$(ls -l $layoutpath | sed '1d' | awk '{ print $9 } ')"

# /home/$USER/scripts/fuzzy "echo \"$layout\" | /home/$USER/scripts/fuzzy_filter LAYOUTS | xargs -I {} sh $layoutpath{}"

source $HOME/scripts/rofi_env
echo "$layout" | rofi -dmenu -theme $dir/"$theme" | xargs -I {} sh $layoutpath{}
