#!/bin/bash
killall -q polybar

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload top > /dev/null 2> /dev/null &
  done
else
  polybar --reload top > /dev/null 2> /dev/null &
fi
