#!/bin/bash
killall -q polybar

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    if [ $m = "HDMI-1" ] || [ $m = "eDP1" ]; then
      MONITOR=$m polybar left > /dev/null 2> /dev/null &
      MONITOR=$m polybar main > /dev/null 2> /dev/null &
      MONITOR=$m polybar right > /dev/null 2> /dev/null &
    else
      MONITOR=$m polybar main_sub > /dev/null 2> /dev/null &
    fi
  done
else
  polybar left > /dev/null 2> /dev/null &
  polybar main > /dev/null 2> /dev/null &
  polybar right > /dev/null 2> /dev/null &
fi
