#!/bin/bash

processes=$(ps -ef | sed '1d' | tr -s " +" " ")

# /home/$USER/scripts/fuzzy "echo \"$processes\" | /home/$USER/scripts/fuzzy_filter PROCESSES | awk '{print $2}' | xargs -I {} sh -c \" [{} -eq ''] && echo 'No process to kill' && exit 1; kill -9 {}\""

# source $HOME/scripts/rofi_env
# theme="style_1"
# echo "$processes" | rofi -dmenu -theme $dir/"$theme"| awk '{print $2}' | xargs -I {} sh -c "[{} -eq ''] && echo 'No process to kill' && exit 1; kill -9 {}"
echo "$processes" | rofi -dmenu | awk '{print $2}' | xargs -I {} sh -c "[{} -eq ''] && echo 'No process to kill' && exit 1; kill -9 {}"
