#!/bin/bash

timeHandle()
{
  if [[ $# -gt 1 ]]; then
    echo "Script Only accept 1 variable"
    exit 1
  fi

  t=$1

  case $t in
    "-h")
      echo "Accept a number to indicate time loop in second. Default is 5 seconds"
      exit 0
      ;;
    *)
      ;;
  esac


  time=5
  if [[ $# == 0 ]]; then
    time=5
  else
    isNum=$(echo "$t" | grep -Po "^[\d]+$" | wc -l)
    if [[ "$isNum" == 0 ]]; then
      echo "Invalid seconds number";
      exit 1
    else
      time=$t
    fi
  fi
}

timeHandle $@

while [[ 1 ==  1 ]]; do
  echo "Time interval is: $time seconds"
  image=$(/home/$USER/scripts/randomImageGet)
  echo "Image: $image"
  feh --bg-fill $image
  # wal -i $image
  sleep $time
done

