#!/bin/python3

import json
import re
import random
from os import system

path = "/home/tnguye20/notes/extra_vocab.md"
# pattern = re.compile(r"^(\w+ \(\w+\)) - ([\w\s,'-]+$)", re.MULTILINE)
pattern = re.compile(r"(\w+ \(\w+\)) - ([\w\s,'-]+)\n([-:',\s\w]+)?$^", re.MULTILINE)

try:
    with open(path, "r") as md:
        data = md.read()
        data = data.split("---")
        data = data[1] if len(data) > 1 else data[0]
        words = pattern.findall(data)
        gameStart = True

        print("""

            Vocabulary Trainer
            Press Enter to see definition and next vocabulary
            Type "clear" to clear screen
            Type "end" to stop Trainer

        """)

        while gameStart:
            rIndex = random.randint(0, len(words) - 1)
            word = words[rIndex][0]
            definition = words[rIndex][1]
            extra = ""
            if len(words[rIndex]) == 3:
                extra = words[rIndex][2]

            value = input("Word: " + word.strip() + "   ")
            value = value.strip()

            if value == "end":
                system('clear')
                print("TRAINER END")
                exit(0)
            if value == "clear":
                system('clear')
            else:
                print("Definition: " + definition.strip())
                if extra != "":
                    print(extra)
                else:
                    print()
                print()
                continue

        md.close()
except KeyboardInterrupt:
    print()
    print("TRAINER END")
    system("clear")
    exit(0)
