#!/bin/sh

wallpaper_path=$HOME/.dotfiles/.wallpaper/
image=`ls -l $wallpaper_path| sed '1d' | awk '{print $9}' | shuf -n 1`
sudo cp $wallpaper_path$image /usr/share/backgrounds/lockscreen.png

i3exit logout
