#!/bin/bash

image=$(/home/$USER/scripts/randomImageGet)
imageName=$(echo $image | grep -Po "(?<=.wallpaper\/)(.*)$")

wal -i $image

notify-send -t 5000 "New wallpaper: $imageName ❤"
echo "$image" | xclip -sel clip
