#!/bin/sh

if [ $# = 0 ];then
  echo "Require Action to Execute"
fi

action=$1

image=$(/home/$USER/scripts/randomImageGet)

sudo cp $image /usr/share/backgrounds/lockscreen.png

if [[ "$action" == "reboot" ]] || [[ "$action" == "shutdown" ]]; then
  rsync -avcXL --delete --progress ~/rsync/ tnguye20@w3.uvm.edu:~/rsync/
fi

i3exit $action
