#!/bin/sh

if [ $# = 0 ];then
  echo "Require Action to Execute"
fi

action=$1

image=$(/home/$USER/scripts/randomImageGet)

sudo cp $image /usr/share/backgrounds/lockscreen.png

if [[ "$action" == "reboot" ]] || [[ "$action" == "shutdown" ]] || [[ "$action" == "logout" ]]; then
  $(/home/$USER/scripts/rsyncFilesTo)
fi

i3exit $action
