#!/bin/sh

repoPath=$HOME/repo/
repos=$(ls -l $repoPath | sed '1d' | awk '{ print $9 } ')

/home/$USER/scripts/fuzzy "echo \"$repos\" | /home/$USER/scripts/fuzzy_filter | xargs -I {} code \"$repoPath{}\""
