#!/bin/bash

process=$(ps -ef | grep randomWallpaperLoop | grep -v "grep" | head -1 | awk '{print $2}')
echo $process
[[ "$process" -ne "" ]] && kill -9 "$process"

nohup $( /home/$USER/scripts/randomWallpaperLoop $1 ) &! >/dev/null 2>&1
