#!/bin/bash

WALL_PATH=$HOME/.dotfiles/.wallpaper/
images=$(ls "$WALL_PATH" | while read A ; do  echo -en "$A\x00icon\x1f$WALL_PATH/$A\n" ; done)

# wal -i $wallpaper_path$image
# feh --bg-fill $wallpaper_path$image

# /home/$USER/scripts/fuzzy "echo \"$images\" | /home/$USER/scripts/fuzzy_filter WALLPAPERS | xargs -I {} sh -c \"/home/$USER/scripts/changeWallpaper $wallpaper_path{} \" "

# source $HOME/scripts/rofi_env
# echo "$images" | rofi -dmenu -theme $dir/"$theme" | xargs -I {} sh -c "$HOME/scripts/changeWallpaper $wallpaper_path{}"
ls -t $WALL_PATH | while read A ; do  echo -en "$A\x00icon\x1f$WALL_PATH/$A\n" ; done | rofi -dmenu | xargs -I {} sh -c "$HOME/scripts/changeWallpaper $WALL_PATH{}"

# echo "$images" | rofi -no-lazy-grab -dmenu -theme $dir/"$theme" | xargs -I {} sh -c "$HOME/scripts/changeWallpaper $wallpaper_path{}"
