#!/bin/bash

wallpaper_path=$HOME/.dotfiles/.wallpaper/
image=$(ls -tl $wallpaper_path | sed '1d' | awk '{ print $9 } ' | dmenu -b -l 9)
imageName=$(echo $image | grep -Po "(?<=.wallpaper\/)(.*)$")


[[ $image -eq "" ]] && exit

wal -i $wallpaper_path$image
notify-send -t 5000 "New wallpaper: $image ❤"
echo "$wallpaper_path$image" | xclip -sel clip
